{
 "title": "WAN Router - CPU & Mem",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "WAN_Router",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.measurementTagValues(\n    bucket: \"telegraf\",\n    measurement: \"Cisco-IOS-XE-process-cpu-oper:cpu-usage/cpu-utilization\",\n    tag: \"source\",\n)\n"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 11, "w": 3, "x": 0, "y": 0 },
   "repeat": "WAN_Router",
   "options": { "content": "<h1>${WAN_Router}</h1>" },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU 5 Sec",
   "type": "stat",
   "gridPos": { "h": 11, "w": 4, "x": 3, "y": 0 },
   "repeat": "WAN_Router",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-process-cpu-oper:cpu-usage/cpu-utilization\")\n  |> filter(fn: (r) => r[\"_field\"] == \"five_seconds\")\n  |> filter(fn: (r) => r[\"path\"] == \"Cisco-IOS-XE-process-cpu-oper:cpu-usage/cpu-utilization\")\n  |> filter(fn: (r) => r[\"source\"] == \"${WAN_Router}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "CPU 1 Min",
   "type": "stat",
   "gridPos": { "h": 11, "w": 4, "x": 7, "y": 0 },
   "repeat": "WAN_Router",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-process-cpu-oper:cpu-usage/cpu-utilization\")\n  |> filter(fn: (r) => r[\"_field\"] == \"one_minute\")\n  |> filter(fn: (r) => r[\"path\"] == \"Cisco-IOS-XE-process-cpu-oper:cpu-usage/cpu-utilization\")\n  |> filter(fn: (r) => r[\"source\"] == \"${WAN_Router}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "CPU 5 Min",
   "type": "stat",
   "gridPos": { "h": 11, "w": 4, "x": 11, "y": 0 },
   "repeat": "WAN_Router",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-process-cpu-oper:cpu-usage/cpu-utilization\")\n  |> filter(fn: (r) => r[\"_field\"] == \"five_minutes\")\n  |> filter(fn: (r) => r[\"path\"] == \"Cisco-IOS-XE-process-cpu-oper:cpu-usage/cpu-utilization\")\n  |> filter(fn: (r) => r[\"source\"] == \"${WAN_Router}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 0 },
   "repeat": "WAN_Router",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-memory-oper:memory-statistics/memory-statistic\")\n  |> filter(fn: (r) => r[\"_field\"] == \"free_memory\" or r[\"_field\"] == \"used_memory\" or r[\"_field\"] == \"total_memory\")\n  |> filter(fn: (r) => r[\"name\"] == \"Processor\")\n  |> filter(fn: (r) => r[\"path\"] == \"Cisco-IOS-XE-memory-oper:memory-statistics/memory-statistic\")\n  |> filter(fn: (r) => r[\"source\"] == \"${WAN_Router}\")\n  |> filter(fn: (r) => r[\"subscription\"] == \"102\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}